
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: regintel
      POSTGRES_USER: regintel
      POSTGRES_PASSWORD: regintel
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  api:
    build: ../
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      DATABASE_URL: postgresql+psycopg2://regintel:regintel@db:5432/regintel
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_PUBLIC_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_RAW: raw-docs
      S3_BUCKET_PDF: rendered-pdfs
    depends_on: [db, redis, minio]
    ports: ["8080:8080"]
    volumes:
      - ../:/app

  workers:
    build: ../
    command: celery -A apps.workers.celery_app worker -l INFO -Q default
    environment:
      DATABASE_URL: postgresql+psycopg2://regintel:regintel@db:5432/regintel
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_RAW: raw-docs
      S3_BUCKET_PDF: rendered-pdfs
    depends_on: [db, redis, minio]
    volumes:
      - ../:/app

volumes:
  dbdata:
  miniodata:
